Numpy

Numpy is a fundamental library for scientific computing in python. 
It provides support for arrays and matrices, along with a collection of mathematical function to operate on these data structure.

In [2]:
import numpy as np   # importing numpy module

print(np.__version__)

array1 = np.array([1, 2, 3, 4, 5])   # creating a numpy array

print(array1)

2.5.3
[1 2 3 4 5]


In [38]:
# Array fundamentals
a = np.array([1,2,3,4,5,6,7,8,9])
a.shape


# array slicing
print(a[:3])

# accessing last element
print(a[-1])



[1 2 3]
9


One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view.

In [41]:
b = a[:5]
print(b)
b[2] = 20

print(a)


[1 2 3 4 5]
[ 1  2 20  4  5  6  7  8  9]


Array attributes

In [49]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a.ndim)

print(a.shape)   # specify the number of elements along with each dimension

print(a.size)   # total number of element

print(a.dtype)

2
(3, 4)
12
int64


How to create a basic array

np.zeros(), np.ones(), np.empty(), np.arrange(), np.linespace()

In [51]:
# np.zeros()
array = np.zeros(4)
print(array)
print(array.dtype)

[0. 0. 0. 0.]
float64


In [55]:
# Create an empty array with 2 elements
print(np.empty(5))

[4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323]


In [57]:
# arange

print(np.arange(10))

print(np.arange(1,10,2))

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [59]:
#  np.linspace() to create an array with values that are spaced linearly in a specified interval

print(np.linspace(0, 10, num=5))

[ 0.   2.5  5.   7.5 10. ]


In [63]:
x = np.ones(4, dtype=np.int64)
print(x)

[1 1 1 1]


In [ ]:
np.zeros((3, 4), dtype=np.int64)

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr)

In [ ]:
## reshape
print(arr.reshape(2, 2))
print(arr)
print(arr.flatten())

Mathematical Operations

In [ ]:
#sum
print(np.sum(arr))

# Mean
print(np.mean(arr))

# median
print(np.median(arr))

# standard deviation
print(np.std(arr))

In [ ]:
np.random.randint(1, 100, size=10)

In [ ]:
print(np.random.seed(42))

Transposing and reshaping a matrix

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

print(data.reshape(2, 3))

print(data.T)  # transpose of the array


print(np.dot(data, data.T))  # dot product of two arrays

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

# commonly used mathematical functions
arr = np.array([1, 2, 3, 4, 5])
print(np.sqrt(arr))  # square root of each element
print(np.log(arr))   # natural logarithm of each element
print(np.exp(arr))   # exponential of each element
print(np.sin(arr))   # sine of each element
print(np.cos(arr))   # cosine of each element
print(np.tan(arr))   # tangent of each element
