Built-in Numpy methods are 100-1000 times faster than python implementation

In [2]:
import numpy as np
import time

In [8]:
# test ans compare  performance of numpy vs plain python loop - dot product

n = 10000000

a = [1] * n
b = [2] * n

start = time.time()
c = [0] * n

for i in range(n):
    c[i] = a[i] * b[i]
end = time.time()
python_list_time = end - start
print("Python list took: ", python_list_time)

numpy_a = np.ones(n)
numpy_b = np.ones(n) * 2
start = time.time()
numpy_c = np.dot(numpy_a, numpy_b)
numpy_time = time.time() - start
print("Numpy took: ", numpy_time)

print("Speedup: ", python_list_time / numpy_time)

Python list took:  1.1776721477508545
Numpy took:  0.01067805290222168
Speedup:  110.28903476455221


In [10]:
#   create 2 matrices using numpy
A = np.array([[1, 2, 3],[0, 1, 0],[0, 0, 1]])
B = np.array([[0, 1, 0],[1, 0, 0],[1, 2, 1]])

In [12]:
# find the sum of two matrix
A + B

array([[1, 3, 3],
       [1, 1, 0],
       [1, 2, 2]])

In [13]:
# difference of two matrix
A - B

array([[ 1,  1,  3],
       [-1,  1,  0],
       [-1, -2,  0]])

In [ ]:
# finding the product of two matrix
A@B

array([[5, 7, 3],
       [1, 0, 0],
       [1, 2, 1]])

In [19]:
# Finding transpose of a matrix
A.T
print(np.transpose(A))

[[1 0 0]
 [2 1 0]
 [3 0 1]]


In [20]:
# Finding determinant of the matrix
print(np.linalg.det(A))

1.0


In [21]:
# finding the inverse of a matrix
print(np.linalg.inv(A))

[[ 1. -2. -3.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [22]:
# Finding the trace of a matrix
print(np.linalg.trace(A))

3


In [23]:
# Finding rank of a matrix
print(np.linalg.matrix_rank(A))

3


In [25]:
# FInding eigen value and Eigen vector of a matrix
print(np.linalg.eig(A))

EigResult(eigenvalues=array([1.+0.j, 1.+0.j, 1.+0.j]), eigenvectors=array([[ 1.00000000e+00+0.j, -1.00000000e+00+0.j, -1.00000000e+00+0.j],
       [ 0.00000000e+00+0.j,  1.11022302e-16+0.j,  0.00000000e+00+0.j],
       [ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  7.40148683e-17+0.j]]))
